#!/usr/bin/env bash

# Script to set up .env file for AMD Ryzen 7 4700U with OpenCL GPU

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
ROOT="$DIR"/../
cd "$ROOT"

echo "Setting up .env file for AMD Ryzen 7 4700U..."

# Create .env file if it doesn't exist
if [ ! -f "$ROOT"/.env ]; then
  echo "# Environment variables for carrotpilot" > "$ROOT"/.env
  echo "# Generated by setup_amd_r7_4700u_device_env.sh" >> "$ROOT"/.env
fi

# Set Python path
echo "Setting PYTHONPATH..."
if grep -q "PYTHONPATH=" "$ROOT"/.env; then
  sed -i 's/.*PYTHONPATH=.*/PYTHONPATH='"$PWD"'/' "$ROOT"/.env
else
  echo "PYTHONPATH=${PWD}" >> "$ROOT"/.env
fi

# Set DEV to CL for OpenCL GPU support
echo "Setting DEV=CL for OpenCL GPU support..."
if grep -q "export DEV=" "$ROOT"/.env; then
  sed -i 's/.*export DEV=.*/export DEV=CL  # Use OpenCL GPU for model inference/' "$ROOT"/.env
else
  echo "export DEV=CL  # Use OpenCL GPU for model inference" >> "$ROOT"/.env
fi

# Enable ZMQ for IPC (required for PC environment)
echo "Enabling ZMQ for IPC..."
if grep -q "export ZMQ=" "$ROOT"/.env; then
  sed -i 's/.*export ZMQ=.*/export ZMQ=1  # Enable ZMQ for IPC/' "$ROOT"/.env
else
  echo "export ZMQ=1  # Enable ZMQ for IPC" >> "$ROOT"/.env
fi

# Enable webcam support
echo "Enabling webcam support..."
if grep -q "export USE_WEBCAM=" "$ROOT"/.env; then
  sed -i 's/.*export USE_WEBCAM=.*/export USE_WEBCAM=1  # Enable USB webcam support/' "$ROOT"/.env
else
  echo "export USE_WEBCAM=1  # Enable USB webcam support" >> "$ROOT"/.env
fi

# Set road camera to default (0)
echo "Setting road camera to default (0)..."
if grep -q "export ROAD_CAM=" "$ROOT"/.env; then
  sed -i 's/.*export ROAD_CAM=.*/export ROAD_CAM=0  # Road camera (dev/video0)/' "$ROOT"/.env
else
  echo "export ROAD_CAM=0  # Road camera (dev/video0)" >> "$ROOT"/.env
fi

# Set parameter directory to project root for PC environment
echo "Setting parameter directory..."
if grep -q "export PARAMS_ROOT=" "$ROOT"/.env; then
  sed -i 's|.*export PARAMS_ROOT=.*|export PARAMS_ROOT='"$PWD"'/data/params  # Parameter directory|' "$ROOT"/.env
else
  echo "export PARAMS_ROOT=${PWD}/data/params  # Parameter directory" >> "$ROOT"/.env
fi

# Set log directories
echo "Setting log directories..."
if grep -q "export LOG_ROOT=" "$ROOT"/.env; then
  sed -i 's|.*export LOG_ROOT=.*|export LOG_ROOT='"$PWD"'/data/realdata  # Log and video storage|' "$ROOT"/.env
else
  echo "export LOG_ROOT=${PWD}/data/realdata  # Log and video storage" >> "$ROOT"/.env
fi

if grep -q "export SWAGLOG_ROOT=" "$ROOT"/.env; then
  sed -i 's|.*export SWAGLOG_ROOT=.*|export SWAGLOG_ROOT='"$PWD"'/data/log  # System log storage|' "$ROOT"/.env
else
  echo "export SWAGLOG_ROOT=${PWD}/data/log  # System log storage" >> "$ROOT"/.env
fi

# Enable human-readable log format
echo "Enabling human-readable log format..."
if grep -q "export LOG_READABLE=" "$ROOT"/.env; then
  sed -i 's/.*export LOG_READABLE=.*/export LOG_READABLE=1  # Human-readable log format/' "$ROOT"/.env
else
  echo "export LOG_READABLE=1  # Human-readable log format" >> "$ROOT"/.env
fi

# Set IMAGE=0 for CL device
echo "Setting IMAGE=0 for CL device..."
if grep -q "export IMAGE=" "$ROOT"/.env; then
  sed -i 's/.*export IMAGE=.*/export IMAGE=0  # Required for OpenCL image handling/' "$ROOT"/.env
else
  echo "export IMAGE=0  # Required for OpenCL image handling" >> "$ROOT"/.env
fi

# Set TG_COMPILE_FLAGS for model compilation on AMD Renoir GPUs
echo "Setting TG_COMPILE_FLAGS for model compilation..."
if grep -q "export TG_COMPILE_FLAGS=" "$ROOT"/.env; then
  sed -i 's/.*export TG_COMPILE_FLAGS=.*/export TG_COMPILE_FLAGS="DEV=CL IMAGE=0 HSA_OVERRIDE_GFX_VERSION=9.0.0"  # Model compilation flags/' "$ROOT"/.env
else
  echo "" >> "$ROOT"/.env
  echo "# Model compilation flags for tinygrad (AMD Renoir GPUs)" >> "$ROOT"/.env
  echo 'export TG_COMPILE_FLAGS="DEV=CL IMAGE=0 HSA_OVERRIDE_GFX_VERSION=9.0.0"' >> "$ROOT"/.env
fi

if grep -q "export TG_COMPILE_FLAGS_BIG=" "$ROOT"/.env; then
  sed -i 's/.*export TG_COMPILE_FLAGS_BIG=.*/export TG_COMPILE_FLAGS_BIG="DEV=CL IMAGE=0 HSA_OVERRIDE_GFX_VERSION=9.0.0"  # Big model compilation flags/' "$ROOT"/.env
else
  echo 'export TG_COMPILE_FLAGS_BIG="DEV=CL IMAGE=0 HSA_OVERRIDE_GFX_VERSION=9.0.0"  # Big model compilation flags' >> "$ROOT"/.env
fi

echo ""
echo ".env file setup complete for AMD Ryzen 7 4700U!"
echo "Contents of .env file:"
echo "======================================"
cat "$ROOT"/.env
echo "======================================"
echo ""
echo "To apply these settings, run: source .env"