#!/usr/bin/env bash

# Script to set up .env file for AMD Ryzen 7 4700U with Radeon Graphics

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
ROOT="$DIR"/../
cd "$ROOT"

echo "Setting up .env file for AMD Ryzen 7 4700U with Radeon Graphics..."

# Create .env file if it doesn't exist
if [ ! -f "$ROOT"/.env ]; then
  echo "# Environment variables for openpilot" > "$ROOT"/.env
  echo "# Generated by setup_device_env.sh for AMD Ryzen 7 4700U with Radeon Graphics" >> "$ROOT"/.env
fi

# Set Python path
echo "Setting PYTHONPATH..."
if grep -q "PYTHONPATH=" "$ROOT"/.env; then
  sed -i 's/.*PYTHONPATH=.*/PYTHONPATH='"$PWD"'/' "$ROOT"/.env
else
  echo "PYTHONPATH=${PWD}" >> "$ROOT"/.env
fi

# Set DEV to AMD for GPU support
echo "Setting DEV=AMD for GPU support..."
if grep -q "export DEV=" "$ROOT"/.env; then
  sed -i 's/.*export DEV=.*/export DEV=AMD  # Use AMD GPU for model inference (Ryzen 7 4700U with Radeon Graphics)/' "$ROOT"/.env
else
  echo "export DEV=AMD  # Use AMD GPU for model inference (Ryzen 7 4700U with Radeon Graphics)" >> "$ROOT"/.env
fi

# Enable ZMQ for IPC
echo "Enabling ZMQ for IPC..."
if grep -q "export ZMQ=" "$ROOT"/.env; then
  sed -i 's/.*export ZMQ=.*/export ZMQ=1/' "$ROOT"/.env
else
  echo "export ZMQ=1  # Enable ZMQ for IPC" >> "$ROOT"/.env
fi

# Enable webcam support
echo "Enabling webcam support..."
if grep -q "export USE_WEBCAM=" "$ROOT"/.env; then
  sed -i 's/.*export USE_WEBCAM=.*/export USE_WEBCAM=1/' "$ROOT"/.env
else
  echo "export USE_WEBCAM=1  # Enable webcam support" >> "$ROOT"/.env
fi

# Set road camera to default (0) and disable other cameras
echo "Setting road camera to default (0)..."
if grep -q "export ROAD_CAM=" "$ROOT"/.env; then
  sed -i 's/.*export ROAD_CAM=.*/export ROAD_CAM=0  # Default road camera setting (dev/video0)/' "$ROOT"/.env
else
  echo "export ROAD_CAM=0  # Default road camera setting (dev/video0)" >> "$ROOT"/.env
fi

# Disable driver camera (set to empty to prevent access to /dev/video2)
echo "Disabling driver camera..."
if grep -q "export DRIVER_CAM=" "$ROOT"/.env; then
  sed -i 's/.*export DRIVER_CAM=.*/export DRIVER_CAM=""  # Disable driver camera/' "$ROOT"/.env
else
  echo "export DRIVER_CAM=""  # Disable driver camera" >> "$ROOT"/.env
fi

# Disable wide camera (set to empty to prevent access to wide camera device)
echo "Disabling wide camera..."
if grep -q "export WIDE_CAM=" "$ROOT"/.env; then
  sed -i 's/.*export WIDE_CAM=.*/export WIDE_CAM=""  # Disable wide camera/' "$ROOT"/.env
else
  echo "export WIDE_CAM=""  # Disable wide camera" >> "$ROOT"/.env
fi

# Set parameter directory to project root for PC environment
echo "Setting parameter directory to project root..."
if grep -q "export PARAMS_ROOT=" "$ROOT"/.env; then
  sed -i 's|.*export PARAMS_ROOT=.*|export PARAMS_ROOT='"$PWD"'/data/params  # Parameter directory for PC environment|' "$ROOT"/.env
else
  echo "export PARAMS_ROOT=${PWD}/data/params  # Parameter directory for PC environment" >> "$ROOT"/.env
fi

# Set log and video storage directories to project root
echo "Setting log and video storage directories..."
if grep -q "export LOG_ROOT=" "$ROOT"/.env; then
  sed -i 's|.*export LOG_ROOT=.*|export LOG_ROOT='"$PWD"'/data/realdata  # Log and video storage directory|' "$ROOT"/.env
else
  echo "export LOG_ROOT=${PWD}/data/realdata  # Log and video storage directory" >> "$ROOT"/.env
fi

if grep -q "export SWAGLOG_ROOT=" "$ROOT"/.env; then
  sed -i 's|.*export SWAGLOG_ROOT=.*|export SWAGLOG_ROOT='"$PWD"'/data/log  # System log storage directory|' "$ROOT"/.env
else
  echo "export SWAGLOG_ROOT=${PWD}/data/log  # System log storage directory" >> "$ROOT"/.env
fi

# Enable human-readable log format
echo "Enabling human-readable log format..."
if grep -q "export LOG_READABLE=" "$ROOT"/.env; then
  sed -i 's/.*export LOG_READABLE=.*/export LOG_READABLE=1  # Enable human-readable log format/' "$ROOT"/.env
else
  echo "export LOG_READABLE=1  # Enable human-readable log format" >> "$ROOT"/.env
fi

# Add AMD-specific optimizations
echo "Adding AMD-specific optimizations..."
if ! grep -q "export AMD_IFACE=" "$ROOT"/.env; then
  echo "export AMD_IFACE=USB  # AMD interface type for Ryzen 7 4700U" >> "$ROOT"/.env
fi

if ! grep -q "export AMD_LLVM=" "$ROOT"/.env; then
  echo "export AMD_LLVM=1  # Enable LLVM for AMD GPU optimization" >> "$ROOT"/.env
fi

echo ""
echo ".env file setup complete for AMD Ryzen 7 4700U with Radeon Graphics!"
echo "Contents of .env file:"
echo "======================================"
cat "$ROOT"/.env
echo "======================================"
echo ""
echo "To apply these settings, run: source .env"